from enum import Enum

class MessageType(Enum):
    AT_WAITING_POSITION = "AT_WAITING_POSITION"
    LOADING_POSITION_VACANT = "LOADING_POSITION_VACANT"
    READY_TO_RECEIVE = "READY_TO_RECEIVE"
    FETCH_BOX = "FETCH_BOX"
    OPERATION_COMPLETE = "OPERATION_COMPLETE"